In [1]:
# now lets build neural ctr 
# first importing the given data set 
# this is a claassification task

In [7]:
import pandas as pd
import numpy as np 
dftrain = pd.read_csv("datasets/train.csv")
dftest = pd.read_csv("datasets/test.csv")
dftrain.isnull().sum()
dftrain.head()
dftrain["label"].unique()

array([0, 1])

In [10]:
dftrain["categorical_feature_17"].unique()
dftrain.columns

Index(['label', 'integer_feature_1', 'integer_feature_2', 'integer_feature_3',
       'integer_feature_4', 'integer_feature_5', 'integer_feature_6',
       'integer_feature_7', 'integer_feature_8', 'integer_feature_9',
       'integer_feature_10', 'integer_feature_11', 'integer_feature_12',
       'integer_feature_13', 'categorical_feature_1', 'categorical_feature_2',
       'categorical_feature_3', 'categorical_feature_4',
       'categorical_feature_5', 'categorical_feature_6',
       'categorical_feature_7', 'categorical_feature_8',
       'categorical_feature_9', 'categorical_feature_10',
       'categorical_feature_11', 'categorical_feature_12',
       'categorical_feature_13', 'categorical_feature_14',
       'categorical_feature_15', 'categorical_feature_16',
       'categorical_feature_17', 'categorical_feature_18',
       'categorical_feature_19', 'categorical_feature_20',
       'categorical_feature_21', 'categorical_feature_22',
       'categorical_feature_23', 'categorical_feature_24',
       'categorical_feature_25', 'categorical_feature_26'],
      dtype='str')

In [15]:
from sklearn.model_selection import train_test_split
train, val = train_test_split(dftrain, test_size=0.176, random_state=42)
train

,label,integer_feature_1,integer_feature_2,integer_feature_3,integer_feature_4,integer_feature_5,integer_feature_6,integer_feature_7,integer_feature_8,integer_feature_9,...,categorical_feature_17,categorical_feature_18,categorical_feature_19,categorical_feature_20,categorical_feature_21,categorical_feature_22,categorical_feature_23,categorical_feature_24,categorical_feature_25,categorical_feature_26
35689,0,87.0,253.0,8.0,NaN,51.0,0.0,0.0,25,0,...,d20856aa,d9f758ff,cc7a7d35,156cbe87,96fbe197,15562d5d,d3df7183,99c2f4d8,30436bfc,e1be5ef2
22376,0,24.0,140.0,NaN,NaN,NaN,NaN,0.0,2,0,...,d20856aa,9ed99e99,cc7a7d35,156cbe87,96fbe197,15562d5d,d3df7183,2a0f0265,cdc3217e,e1be5ef2
2733,0,NaN,46.0,2.0,3.0,5.0,4.0,0.0,1,6,...,NaN,7232d217,108a0699,47849e55,73b3f46d,d994ba60,NaN,ab5fae3b,ff654802,2ba8d787
6194,0,2.0,524.0,3.0,196.0,2.0,0.0,0.0,64,11,...,NaN,b8170bba,9512c20b,e200b692,d130f00a,2ff28449,NaN,cb728d59,30436bfc,ed10571d
10098,0,23.0,506.0,6.0,NaN,NaN,0.0,0.0,0,11,...,NaN,628f1b8d,09c8c22c,47849e55,73b3f46d,d994ba60,NaN,3935baca,ff654802,b757e957
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6265,0,32.0,1250.0,16.0,NaN,NaN,0.0,0.0,831,1,...,d20856aa,b7771e51,cc7a7d35,156cbe87,96fbe197,15562d5d,d3df7183,c1c983cb,30436bfc,e1be5ef2
11284,0,4.0,344.0,NaN,NaN,19.0,0.0,0.0,219,3,...,d20856aa,b8170bba,cc7a7d35,156cbe87,96fbe197,15562d5d,d3df7183,230eb28f,30436bfc,e1be5ef2
38158,0,NaN,13.0,NaN,NaN,NaN,NaN,0.0,1252,0,...,NaN,b8170bba,9512c20b,f7cc74d5,7ccb16d8,0318741b,NaN,058fe9e4,321935cd,b757e957
860,1,1.0,151.0,2.0,603.0,12.0,0.0,0.0,1,15,...,NaN,53ad3ad6,09c8c22c,47849e55,73b3f46d,d994ba60,NaN,59c61d47,ff654802,b757e957
15795,0,38.0,100.0,28.0,45.0,4.0,36.0,0.0,6,43,...,NaN,c013b6d8,9512c20b,35f5f3cf,c19932db,368c0159,NaN,7cc1f2ce,30436bfc,962813c6

In [18]:
integer_cols = [f'integer_feature_{i}' for i in range(1, 14)]
categorical_cols = [f'categorical_feature_{i}' for i in range(1, 27)]


for col in integer_cols:
    train_median = train[col].median()
    train[col] = train[col].fillna(train_median)
    val[col] = val[col].fillna(train_median)
    dftest[col] = dftest[col].fillna(train_median)


for col in categorical_cols:
    train[col] = train[col].fillna("MISSING")
    val[col] = val[col].fillna("MISSING")
    dftest[col] = dftest[col].fillna("MISSING")

In [24]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
# here it is only fiting 

train[integer_cols] = scaler.fit_transform(train[integer_cols])
val[integer_cols] = scaler.transform(val[integer_cols])
dftest[integer_cols] = scaler.transform(dftest[integer_cols])

now we encode the catagorical data so that we can make a embedding layer in the nn

In [31]:
cardinalities = {}
    
    
train_encoded = train.copy()
val_encoded = val.copy()
test_encoded = dftest.copy()
for col in categorical_cols:
    # here i am taking only train data coz to prevent data leakage 
    unique_categories = sorted(train_encoded[col].unique()) 
    if "MISSING" in unique_categories:
            unique_categories.remove("MISSING")


    category_to_idx = {"MISSING": 0}
    for idx, cat in enumerate(unique_categories, start=1):
        category_to_idx[cat] = idx

    cardinalities[col] = len(category_to_idx)


    train_encoded[col] = train_encoded[col].map(category_to_idx).fillna(0).astype(int)
    val_encoded[col] = val_encoded[col].map(category_to_idx).fillna(0).astype(int)
    test_encoded[col] = test_encoded[col].map(category_to_idx).fillna(0).astype(int)

In [32]:
cardinalities

{'categorical_feature_1': 11141,
 'categorical_feature_2': 3440,
 'categorical_feature_3': 4635,
 'categorical_feature_4': 1648,
 'categorical_feature_5': 3720,
 'categorical_feature_6': 4,
 'categorical_feature_7': 2932,
 'categorical_feature_8': 717,
 'categorical_feature_9': 23,
 'categorical_feature_10': 9852,
 'categorical_feature_11': 4869,
 'categorical_feature_12': 6947,
 'categorical_feature_13': 10,
 'categorical_feature_14': 838,
 'categorical_feature_15': 1881,
 'categorical_feature_16': 40,
 'categorical_feature_17': 4,
 'categorical_feature_18': 314,
 'categorical_feature_19': 15,
 'categorical_feature_20': 11393,
 'categorical_feature_21': 7753,
 'categorical_feature_22': 10693,
 'categorical_feature_23': 4459,
 'categorical_feature_24': 3295,
 'categorical_feature_25': 35,
 'categorical_feature_26': 25}

In [33]:
train_encoded

,label,integer_feature_1,integer_feature_2,integer_feature_3,integer_feature_4,integer_feature_5,integer_feature_6,integer_feature_7,integer_feature_8,integer_feature_9,...,categorical_feature_17,categorical_feature_18,categorical_feature_19,categorical_feature_20,categorical_feature_21,categorical_feature_22,categorical_feature_23,categorical_feature_24,categorical_feature_25,categorical_feature_26
35689,0,0.105261,-0.202762,0.200575,-0.136257,0.621023,-0.245114,-0.093173,-0.232651,-0.816294,...,3,264,12,945,4602,910,3697,2003,4,21
22376,0,-0.012807,-0.370036,-0.288474,-0.136257,-0.181853,-0.245114,-0.093173,-0.291204,-0.816294,...,3,191,12,945,4602,910,3697,558,22,21
2733,0,-0.042792,-0.509184,-0.532998,-0.193167,-0.199695,0.413720,-0.093173,-0.293750,-0.331626,...,0,133,3,3200,3558,9054,0,2220,34,3
6194,0,-0.054037,0.198398,-0.410736,0.185576,-0.253220,-0.245114,-0.093173,-0.133365,0.072264,...,0,225,10,10001,6316,1967,0,2619,4,22
10098,0,-0.014681,0.171753,-0.043949,-0.136257,-0.181853,-0.245114,-0.093173,-0.296296,0.072264,...,0,115,1,3200,3558,9054,0,750,34,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6265,0,0.002186,1.273093,1.178674,-0.136257,-0.181853,-0.245114,-0.093173,1.819254,-0.735516,...,3,222,12,945,4602,910,3697,2514,4,21
11284,0,-0.050288,-0.068055,-0.288474,-0.136257,0.050089,-0.245114,-0.093173,0.261232,-0.573960,...,3,225,12,945,4602,910,3697,459,4,21
38158,0,-0.042792,-0.558033,-0.288474,-0.136257,-0.181853,-0.245114,-0.093173,2.891031,-0.816294,...,0,225,10,11015,3824,117,0,78,6,17
860,1,-0.055911,-0.353753,-0.532998,0.984273,-0.074803,-0.245114,-0.093173,-0.293750,0.395376,...,0,95,1,3200,3558,9054,0,1184,34,17
15795,0,0.013430,-0.429248,2.645821,-0.110746,-0.217537,5.684387,-0.093173,-0.281021,2.657159,...,0,237,10,2403,5879,2250,0,1636,4,12